name: Electron CI build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://stg-gke-eu.voxeet.net/nexus/repository/npm-group/'
        always-auth: true
    - name: Download DVEF
      run: |
          Invoke-WebRequest http://voxeet-io-electron-ci.s3.amazonaws.com/DVEF_build_${{ runner.os }}.zip -OutFile out.zip
          Expand-Archive out.zip -DestinationPath dvef -Force
      shell: pwsh
    - name: install dependencies
      run: |
          yarn install
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUS_AUTH_TOKEN }}
    - name: update version
      run: |
          yarn version --no-git-tag-version --new-version "$(npm run --silent get-version)-$($env:GITHUB_REF.replace('refs/heads/',''))"
          npm run get-version
      shell: pwsh
    - name: build/release Electron app
      run: |
          yarn run build:electron
          yarn run electron-builder --publish always -c.electronDist=dvef
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NEXUS_AUTH_TOKEN }}
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
